### PR TITLE
Redundant delegate creation

### PR DESCRIPTION
**Pull request by Kavignon**

### CODE REVIEW

**Comment by Kavignon** [comment]
Can you simply look at the code. I will rebase this branch too
I've just figured out that I'm really out of sync !!

**Comment by mkrueger** [comment]
you're opening pull requests to the wrong branch. You need to open them against the roslyn one.

**Comment by Kavignon** [comment]
I've just updated my fork project. These are the actual branches that my
project can see : master, roslyn and roslyn-tarball-nuget-restore. I don't
see any roslyn one

**Comment by mkrueger** [comment]
https://github.com/icsharpcode/NRefactory/tree/roslyn

**Comment by Kavignon** [comment]
Hi Mike,

Every single time I try to create a branch from my roslyn branch or latest
commit, I also get a branch which is too old when compared to the actual
branch on the project. I have updated my forked project two times since I
started the project. I have an "upstream" and a "roslynstream" thanks to
this link :
https://stackoverflow.com/questions/7244321/how-to-update-github-forked-repository

But even branches from those don't work. It actually sucks a bit that I
don't know what to do in order to show what I've did in the previous days.
Can you help me out a bit and tell me what I have to do so I won't mess up
like this again?

Thank you very much !

**Comment by mkrueger** [comment]
Hi

Create a new remote for the real repository
Check out the roslyn branch from that new remote & merge it to yours.

And open the pull request to the roslyn branch - not master.

Regards
Mike

**Comment by Kavignon** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- Kevin

Confirm that you know Kevin: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=KnZx2Yte&invitationId=6208290943595016192&trk=eml-guest-invite-cta&trkEmail=eml-invite_guest-null-2-null-null-0%7Eivzc5ee4%7Ei1








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ivzc5ee4-i1&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQEwB86vj4I0AQAAAVihH1VIgVSQ_5i3-QHZ6rXck9lo5oilqqI2RoGav8NjBXp8v_UDtREYhAD14koEMjlVqbQXRO9TSASq7rwcW2anXuz9eEi4e-AJY7OaF-3v18loyoPe6ZbYN3z_MtZRalXHCsvQTXx2j93RKitTZrzb-27lpKVRKIK1C37NOSke7onar2wMyy2r-vC3syCtJgpMS6Zx4w&eid=0-ivzc5ee4-i1


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ivzc5ee4-i1&a=customerServiceUrl&ek=invite_guest

© 2016 LinkedIn Corporation, 1000 West Maude Avenue, Sunnyvale, CA 94085. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by Kavignon** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- Kevin

Confirm that you know Kevin: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=BccC05QR&invitationId=6208290943301410816&trk=eml-guest-invite-cta&trkEmail=eml-invite_guest-null-2-null-null-0%7Eivzc5h71%7Equ








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ivzc5h71-qu&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQEo7TptRVzvLgAAAVihH1dLgpXRaazYiuuFbUY6u3pzp-X16QDbuQdWXJh3Z6Gi7Wtq2uLfa8AY85MB0ggAOJ4AiYsmS0XR4QuXsDPNzoyvwe_qNep9mEqQjge8hNw-GC6HIcUttcD1R_TjaKtphD2VE2Be9Mx-XlYAdt7SMensqerLtv8n59agLguDvtGD59-FpWBi8EhJ1PaXw_XVCVq0PA&eid=0-ivzc5h71-qu


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ivzc5h71-qu&a=customerServiceUrl&ek=invite_guest

© 2016 LinkedIn Corporation, 1000 West Maude Avenue, Sunnyvale, CA 94085. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by Kavignon** [comment]
Kevin Avignon would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=BccC05QR&invitationId=6208290943301410816&trk=eml-first_guest_reminder_01-hero-121-accept_text&trkEmail=eml-first_guest_reminder_01-hero-121-accept_text-null-%7E7jx7nr%7Eiw6mrfd6%7E7o

View Kevin Avignon&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=BccC05QR&invitationId=6208290943301410816&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-%7E7jx7nr%7Eiw6mrfd6%7E7o





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-7jx7nr-iw6mrfd6-7o&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=123&m=unsub&ts=HTML&eid=-7jx7nr-iw6mrfd6-7o&loid=AQEtnLcQSkeEMAAAAVi8Min9c0Fc4apq6l5rYS8cb1Qr-5QqZYl_DbxOdmxO9Ba2lpYoLCreIbMpBnQFnNhLkw8KOlYNqqoxVnlmZSOXTUdvfC6ona9iUbKfIAI4DI1H8diLgglp_AWuz3U8uZbbIkzAJDYLwFer0Yjx1tY181FQ7RVYmTpjMrXivvZasDjnx7oKf-7sttASlbbj7aefTI9qDry9pw

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-7jx7nr-iw6mrfd6-7o&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by Kavignon** [comment]
Kevin Avignon would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=KnZx2Yte&invitationId=6208290943595016192&trk=eml-first_guest_reminder_01-hero-121-accept_text&trkEmail=eml-first_guest_reminder_01-hero-121-accept_text-null-cov5s8%7Eiw6msi4s%7E5w

View Kevin Avignon&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=KnZx2Yte&invitationId=6208290943595016192&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-cov5s8%7Eiw6msi4s%7E5w





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=cov5s8-iw6msi4s-5w&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=123&m=unsub&ts=HTML&eid=cov5s8-iw6msi4s-5w&loid=AQFK95ld8hzFrQAAAVi8PzRvvb7NnZ7Akx0Qx4sUORZHM4OU2HDWeAyyjFPjgl_H0MqpssEmIFIHr81BfkuNuabYHJfKs9bw0_L_p3NCqcosNkwPeVBwxlZH9W3EcRnNHMJg8_oF072rKa7G0S49mrPzN_D1wGVzSnFiENbPNN6lUynmCdJRHGFZ9uu_blSvEVEEjEHoKgKKL1AkfPrn7vlQ92HvHg

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=cov5s8-iw6msi4s-5w&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Pull request closed without merging**
