### PR TITLE
Ported LockThisAnalyzer with Roslyn  using the following

### PR DESCRIPTION
**Pull request by Kavignon**
An helper method to validate that the lockstatement does contain, or not, a this expression syntax
An helper method to validate that a attribute is of type MethodImpl and that the user accesses the enum value of Synchronized in MethodImplOptions

For now, most of the tests are failing because of the text span that I'm giving but I don't know what is wrong and I would need some help with it.

The test TestMethodHasSynchronized gives me an headache.
Breaks my code as when using | does not allow any simple member access expression. I would need to use a BinaryExpressionSyntax to get access to the left/right members. Do I need to make a big recursion code for those cases or just have a simple binary that I would then break in its members to get my hands on the member access expressions and then follow the same logic that I had

As for the code fix provider, I don't really know how it is realy done. I have started to modify it, but I would need some guidance to know how to do them in the future.

### CODE REVIEW

**Comment by Kavignon** [comment]
So, if I sum up what you told me I should:

-Add a message for the code fix and delete the {0}. I don't really know what happened there, I'll fix it !
-Go see other code fix that don't have the attribute NotPortedYet and change the code fix to do what needs to be done
-Instead of doing my work in a helper method, I should analyze lock statement directly in my TryDiagnostic. I don't understand the statement that you said: "stmt.Expression.SkipParens().IsKind (SyntaxKind.ThisExpression);"

The solution with the keyvaluepair was that since I have to types of syntax to look for, not only I can know that I can validate the need for a diagnostic and where to give its position without having to cast my node in the try diagnostic method.

How would you like me to refactor my solution?

**Comment by Kavignon** [comment]
TestMethodHasSynchronized 

I've analyze the attribute with the rolsyn window. When I get to the AttributeArgument level within my AttributeSyntax, I don't have a Simple Member Access syntax like I did with the other tests. Instead, I ended up with BitwiseExpression which is a BinaryExpresionSyntax. When looking at that binary expression, I noted that the left and right member of this expression did contain the SimpleMemberAccessExpressions that I wanted.

My question for you was intended like the following : Should I only care to work with only a single binary expression syntax or should I develop an algorithm which would analyze the simple member access expression on the left and analyze the right member to see if it's a binary expression or a simple member access. To sum up, my question should put like this : " Should I only look for a single binary expression of should I develop a recursion method to look for every binary expression within my attribute argument until I find the value I seek ?

**Comment by mkrueger** [comment]
> -Add a message for the code fix and delete the {0}. I don't really know what happened there, I'll fix it !

There were 2 different messages that's why {0} is used - the create
diagnostic can take message format arguments.

> -Instead of doing my work in a helper method, I should analyze lock statement directly in my TryDiagnostic. I don't understand the statement that you said: "stmt.Expression.SkipParens().IsKind (SyntaxKind.ThisExpression);"

Just try this expression.

> The solution with the keyvaluepair was that since I have to types of syntax to look for, not only I can know that I can validate the need for a diagnostic and where to give its position without having to cast my node in the try diagnostic method.
> 
> How would you like me to refactor my solution?

Just try what I suggested - remove the method and take the expression
above for the 'this' validition - the code is much more readable.
KeyValue pairs are generally bad for that kind because the meaning of
Key and Value is what you're assigning them to -it's not clear for what
that stands.
I know it's a often used hack but I would discourage to use that because
it's bad behavior.

**Comment by mkrueger** [comment]
> " Should I only look for a single binary expression of should I develop a recursion method to look for every binary expression within my attribute argument until I find the value I seek ?  

I think you're referring to the :

[MethodImpl (Value = MethodImplOptions.Synchronized)]

Attribute - des that needs to be analyzed. But a foreach would be enough
- the Attribute surely has an Arguments property which you can use.

**Comment by Kavignon** [comment]
I was refering to something that looks like this : " [MethodImpl (MethodImplOptions.Synchronized | MethodImplOptions.NoInlining)]"

**Comment by Kavignon** [comment]
Except that binary expression which could "cause trouble" in my algorithm for attribute, I think the code I wrote should go just fine !

**Comment by mkrueger** [comment]
> I was refering to something that looks like this : " [MethodImpl (MethodImplOptions.Synchronized | MethodImplOptions.NoInlining)]" 

You could resolve this and get the ConstantValue. May be easier.

**Comment by Kavignon** [comment]
i don't quite get what you mean by resolve this?  What is a ConstantValue? Is there documentation I could read on the matter or is there any sample code within the code base?

**Comment by mkrueger** [comment]
> i don't quite get what you mean by resolve this?  What is a ConstantValue? Is there documentation I could read on the matter or is there any sample code within the code base? 

Just use the semanticmodel object that'll give any semantic information.

**Pull request closed without merging**
