### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by luca-saggese**
Visual basic support,
sorry i'm new with git, now should be ok

### CODE REVIEW

**Comment by mkrueger** [comment]
Thanks - git is really nice but very complex :)

**Comment by luca-saggese** [comment]
Thanks Mike,
i’m working in creating the binding for monodevelop, but i found it very hard because most of the classes are different from old nrefactoring (V5) code (one for all is AstNode, now SyntaxNode, but also many more) could you point me to the right direction?


-- 
Luca Saggese

Il giorno 20 gennaio 2015 @ 09:21:21, Mike Krüger (notifications@github.com) ha scritto:

Merged #458.

**Comment by mkrueger** [comment]
monodevelop roslyn is developed in another branch which is not yet public :/.

**Comment by luca-saggese** [comment]
Will wait for it then, or add me if possible
-- 
Luca Saggese

Il giorno 22 gennaio 2015 @ 15:30:25, Mike Krüger (notifications@github.com) ha scritto:

monodevelop roslyn is developed in another branch which is not yet public :/.

**Pull request merged**
