### PR TITLE
NRefactory6

### PR DESCRIPTION
**Pull request by Kavignon**

### CODE REVIEW

**Comment by mkrueger** [comment]
Commits from master --> roslyn are a bad idea as well. 
Both branches are too different. The only thing they could share is potentially the unit tests.

Therefore : Do no auto merge these branches. They're basically incompatible.

**Comment by Kavignon** [comment]
Instead of pull request, could I simply do a fork ?

**Comment by Kavignon** [comment]
Or would it be better to have my own branch ?

**Comment by mkrueger** [comment]
What are you trying to do ? 

In general it's better if you fork and have your own branch and make pull requests from that to the branch you're working on.

**Comment by Kavignon** [comment]
Kevin would like to stay in touch on LinkedIn.

Kevin Avignon
Senior Software Engineer Student 
Montreal, Canada Area

View profile https://www.linkedin.com/e/v2?e=0-ivzc7ggw-4f&a=publicProfile&tracking=eml-guest-invite-pprofile-link-cta&ek=invite_guest&vanityName=kevinavignon

Confirm that you know Kevin https://www.linkedin.com/comm/start/accept-invitation?sharedKey=hNJoKxXe&invitationId=6208290943687282690&trk=eml-guest-invite-cta&trkEmail=eml-invite_guest-null-112-null-null-0%7Eivzc7ggw%7E4f


.....................................

Unsubscribe: https://www.linkedin.com/e/v2?e=0-ivzc7ggw-4f&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&li=119&m=unsub&ts=unsub&loid=AQFIidSwkI35_wAAAVihIMhDLF2hlMI8qmXq7zZ3CIXNlo_GoxEw-xVYcEz5ftNEcVl_cTlWQ4qBKVXJKFJKZ8nJBjZ9uM03i2Ynt0j_7auuR5XAeXd0kqs0hVMSGNQ83FMj_kZnZ4JCUm9m9LUasv9vJbqnvWop15q95aOfLz47N0q3PWHtfE9STs57lgyta21swF-K52bQbY0mBuvkjVHfPw&eid=0-ivzc7ggw-4f

Help: https://www.linkedin.com/e/v2?e=0-ivzc7ggw-4f&a=customerServiceUrl&ek=invite_guest&li=118&m=footer&ts=help&articleId=67


You are receiving Invitation emails. LinkedIn will use your email address to make suggestions to our members in features like People You May Know.

This email was sent to reply@reply.github.com.

© 2016 LinkedIn Ireland Unlimited Company, Wilton Plaza, Wilton Place, Dublin 2. LinkedIn is a registered business name of LinkedIn Ireland Unlimited Company. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by Kavignon** [comment]
Kevin Avignon would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=hNJoKxXe&invitationId=6208290943687282690&trk=eml-first_guest_reminder_01-hero-121-accept_text&trkEmail=eml-first_guest_reminder_01-hero-121-accept_text-null-%7Ea92j94%7Eiw6msic6%7Ec8

View Kevin Avignon&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=hNJoKxXe&invitationId=6208290943687282690&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-%7Ea92j94%7Eiw6msic6%7Ec8





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-a92j94-iw6msic6-c8&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=123&m=unsub&ts=HTML&eid=-a92j94-iw6msic6-c8&loid=AQEYmpuvWVvCfQAAAVi8NrcGmh51uFJgOiwdzqd8Yh13CeLYGUPHZw-MfHNb0x_9lm23vH8koCBbft1TJDbqVsHJwqfA4zsy7x4jdG67-Zh9MX5PMuxZ8SioXvwPPM0ef5lmD_Nqk8n-talYUOAeXVZgVlHxGWCZ_-jucDeghiT9J7mYkdnhE0orTAdLs9VjWPmvvHYi1zV3BLaYg-_mW68jS627lA

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-a92j94-iw6msic6-c8&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Pull request closed without merging**
