### PR TITLE
New pull request for the lock this

### PR DESCRIPTION
**Pull request by Kavignon**
Code fix provider still lacking at the moment
Will be working on this on a latter moment.

### CODE REVIEW

**Comment by mkrueger** [comment]
That's atm very empty - missing some files ?

**Comment by Kavignon** [comment]
you were right. I don't know what happened there. I made a commit

**Comment by Kavignon** [comment]
I made the commit on the wrong branch (the third one)
I would like to know, except for the roslyn branch which is up to date, every single new branch I created at the same point where roslyn was is still 107 commits behind.
Why are all my branches out of sync if roslyn is ok ? More than that, when I tried to compare one of my new branches, it compared with the master and not the roslyn

**Comment by Kavignon** [comment]
WHat I wanted to do was create a new branch for each element I ported. We could just quickly evaluate in this branch the ported elements. WHen you give me the appreciation and guidance, I'll close here and make a new PR for the next element?
Or is there a way to make my other branches ok?

**Pull request closed without merging**
